# Generated by Django 5.2.4 on 2025-08-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedCompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Banned company name',
                'verbose_name_plural': 'Banned company names',
            },
        ),
        migrations.CreateModel(
            name='MassmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_per_day', models.PositiveIntegerField(default=94, help_text='Daily message limit for email accounts.')),
                ('use_business_time', models.BooleanField(default=False, help_text='Send only during business hours.')),
                ('business_time_start', models.TimeField(default='08:30', help_text='Start of working hours.')),
                ('business_time_end', models.TimeField(default='17:30', help_text='End of working hours.')),
                ('unsubscribe_url', models.URLField(default='https://www.example.com/unsubscribe', help_text='"Unsubscribed successfully" page."')),
            ],
            options={
                'verbose_name': 'Massmail Settings',
                'verbose_name_plural': 'Massmail Settings',
            },
        ),
        migrations.CreateModel(
            name='PublicEmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=20, unique=True, verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Public email domain',
                'verbose_name_plural': 'Public email domains',
            },
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_interval', models.PositiveBigIntegerField(default='300', help_text="Specify the interval in seconds to check if it's time for a reminder.", verbose_name='Check interval')),
            ],
            options={
                'verbose_name': 'Reminder settings',
                'verbose_name_plural': 'Reminder settings',
            },
        ),
        migrations.CreateModel(
            name='StopPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100, unique=True, verbose_name='Phrase')),
                ('last_occurrence_date', models.DateField(auto_now=True, help_text='Date of last occurrence of the phrase', verbose_name='Last occurrence date')),
            ],
            options={
                'verbose_name': 'Stop Phrase',
                'verbose_name_plural': 'Stop Phrases',
            },
        ),
    ]
